# SPDX-FileCopyrightText: none
# SPDX-License-Identifier: CC0-1.0

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  Thanks for opening your first issue here! Be sure to follow the issue template!

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  Welcome to the community and thanks for opening your first pull request.
  Feel free to look for more issues to tackle at https://github.com/DinoTools/dionaea/issues

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
# firstPRMergeComment: >
#   Congrats on merging your first pull request! We here at behaviorbot are proud of you!

# It is recommend to include as many gifs and emojis as possible
